import {
  Home,
  Leadership,
  LoginWithOtp,
  PoetDetails,
  ViewAllPoet,
  ViewAllOccasion,
  OccasionDetails,
  SubCategoryDetails,
  ViewAllSubCategory,
  LoginPage,
  SignUpPage,
  Profile,
  EditProfile,
  QRCodeDownload,
  LoginActivity,
  NotificationPermission,
  BlockAccount,
  AccountPrivacy,
  ManageAccount,
  PersonalDetails,
  DiaryByType,
  AboutUs,
  Brand,
  WorkingAtBlackDiary,
} from "./pages/Index";

export const publicRoutes = [
  { path: "/login-diary", component: LoginPage, exact: true },
  { path: "/login", component: LoginPage, exact: true },
  { path: "/signup", component: SignUpPage, exact: true },
  { path: "/signUp-diary", component: SignUpPage, exact: true },
  { path: "/signUp-otp/:id?", component: LoginWithOtp, exact: true },
  { path: "/", component: Home, exact: true },
  { path: "/poets/details/:slug?/:id?", component: PoetDetails, exact: true },
  { path: "/poets", component: ViewAllPoet, exact: true },
  { path: "/occasion", component: ViewAllOccasion, exact: true },
  { path: "/occasion/details/:slug?/:id?", component: OccasionDetails, exact: true },
  { path: "/sub-category/details/:slug?/:id?", component: SubCategoryDetails, exact: true },
  { path: "/search/sub-category", component: ViewAllSubCategory, exact: true },
  { path: "/leadership", component: Leadership, exact: true },
  { path: "/about-us", component: AboutUs, exact: true },
  { path: "/brand", component: Brand, exact: true },
  { path: "/working-at-black-diary", component: WorkingAtBlackDiary, exact: true },
];

export const privateRoutes = [
  { path: "/profile/:username?/:id?", component: Profile, exact: true },
  { path: "account/edit-profile/:username?/:id?", component: EditProfile, exact: true },
  { path: "account/qr-code/:username?/:id?", component: QRCodeDownload, exact: true },
  { path: "account/login-activity/:username?/:id?", component: LoginActivity, exact: true },
  {
    path: "account/notification-permission/:username?/:id?",
    component: NotificationPermission,
    exact: true,
  },
  { path: "account/block-account/:username?/:id?", component: BlockAccount, exact: true },
  { path: "account/privacy-account/:username?/:id?", component: AccountPrivacy, exact: true },
  { path: "account/manage-account/:username?/:id?", component: ManageAccount, exact: true },
  { path: "account/personal-details/:username?/:id?", component: PersonalDetails, exact: true },
  { path: "/diary-by-type/:type?", component: DiaryByType, exact: true },
];
